from . import account_move
from . import res_partner
from . import sale_order
from . import res_company
from . import product_template
from . import account_analytic_account
from . import sale_order_line
from . import subscription_state
from . import sale_subscription_plan
from . import contract_type
from . import organization_type
from . import broker_entity
from . import property_type
from . import nationality_type
from . import title_deed_type
from . import lessor_representative
from . import dashboard