{
    'name': 'Vendor Payment Employee & Department',
    'version': '1.0',
    'category': 'Accounting',
    'summary': 'Add Employee and Department to Vendor Payments',
    'depends': ['account', 'hr'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'reports/report_payment_reciept.xml',
        'reports/report_expense_sheet_replace.xml',
        'views/account_payment_view.xml',
        'views/kind_of_payment_model.xml',
        'views/expense.xml',
        'views/purchase_order.xml',
        'views/multi_payment.xml',
        'views/allowed_confirm.xml',
    ],
    'installable': True,
    'application': True,
}
